/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import db.DBUtility;
import domain.ClassInfo;
import java.awt.Dimension;
import java.time.Duration;
import java.time.Instant;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.neo4j.ogm.exception.ConnectionException;
import parser.CustomProjectClassParser;
import utils.Globals;
import utils.ResultsLogger;
import utils.SwingWorker;

/**
 *
 * @author Fede
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // set the jframe size and location, and make it visible
        setPreferredSize(new Dimension(900, 550));
        pack();
        setLocationRelativeTo(null);
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(LoadCode.class.getName()).log(Level.SEVERE, null, ex);
        }
        ResultsLogger.init(txtLogger);
        Globals.getSparkContext();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        txtProjectUrl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnProcesar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnProcesarPara = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLogger = new javax.swing.JEditorPane();
        bottonPanel = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        topPanel.setPreferredSize(new java.awt.Dimension(0, 80));
        topPanel.setLayout(null);

        txtProjectUrl.setPreferredSize(new java.awt.Dimension(5, 18));
        topPanel.add(txtProjectUrl);
        txtProjectUrl.setBounds(20, 30, 390, 25);

        jLabel1.setText("Seleccion de proyecto");
        topPanel.add(jLabel1);
        jLabel1.setBounds(20, 10, 290, 20);

        btnProcesar.setText("Procesar(Hilos)");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });
        topPanel.add(btnProcesar);
        btnProcesar.setBounds(550, 30, 120, 25);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        topPanel.add(btnBuscar);
        btnBuscar.setBounds(420, 30, 120, 25);

        btnProcesarPara.setText("Procesar(Paralelismo)");
        btnProcesarPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarParaActionPerformed(evt);
            }
        });
        topPanel.add(btnProcesarPara);
        btnProcesarPara.setBounds(680, 30, 150, 25);

        getContentPane().add(topPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        centerPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(txtLogger);

        centerPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        bottonPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bottonPanel.setPreferredSize(new java.awt.Dimension(50, 50));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        bottonPanel.add(btnCerrar);

        getContentPane().add(bottonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        new SwingWorker() {
            @Override
            public Object construct() {
                process(false);
                return null;
            }

            @Override
            public void finished() {
            }
        }.start();

    }//GEN-LAST:event_btnProcesarActionPerformed

    private void process(boolean para) {
        txtLogger.setText("");
        if (txtProjectUrl.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Carpeta de proyecto requerida", "Carpeta de proyecto requerida", JOptionPane.ERROR_MESSAGE);
            txtProjectUrl.requestFocus();
            return;
        }
        Instant start = Instant.now();
        Map<String, ClassInfo> results = para ? process.ProcessSpark.process(txtLogger, txtProjectUrl.getText())
                : process.Process.process(txtLogger, txtProjectUrl.getText());
        try {
            if (para) {
                DBUtility.insert();
            } else {
                DBUtility.insert(results);
            }
            ResultsLogger.doLog("DATOS INSERTADOS EXISTOSAMENTE!!"+ResultsLogger.LINE_BREAK);
            Instant end = Instant.now();
            Duration interval = Duration.between(start, end);
            ResultsLogger.doLog("Execution time in seconds: " + interval.getSeconds());

        } catch (ConnectionException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            ResultsLogger.doLog("Error,existe un problema de comunicacion con la base de datos, favor asegurarse que neo4j esta corriendo",true);
        }

    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        JFileChooser f = new JFileChooser();
        f.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        f.showSaveDialog(null);
        txtProjectUrl.setText(f.getSelectedFile() == null ? "" : f.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnProcesarParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarParaActionPerformed
        process(true);

    }//GEN-LAST:event_btnProcesarParaActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
    this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed
    
    @Override
    public void dispose(){
        CustomProjectClassParser.deleteTempFolder();
        super.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    static void displayJFrame() {
        // create our jframe as usual

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottonPanel;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnProcesarPara;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel topPanel;
    private javax.swing.JEditorPane txtLogger;
    private javax.swing.JTextField txtProjectUrl;
    // End of variables declaration//GEN-END:variables
}
